### ISSUE TITLE
Could not connect to Playdate Simulator

### ISSUE THREAD

**Issue by Tajfun86** [midouest/vscode-playdate-debug#13]
Hey,
Every time I try to use "Playdate: Debug" via F5, I get a popup saying, "could not connect to Playdate Simulator"
Despite that game starts in the simulator, but it does not trigger any breakpoints.

I'm trying to run Lua game with:
vscode 1.74.2
PlaydateSDK 1.12.3

**Comment by midouest** [comment]
Hey! What operating system are you developing on?

**Comment by Tajfun86** [comment]
Windows 11 (ver. 22h2)

**Comment by midouest** [comment]
The Playdate SDK version 1.12.3 and earlier only supports debugging on macOS. Unfortunately debugging is not yet available on Windows in the public SDK version. It will be available in Playdate SDK version 1.13+.

You can prevent the error by using the build keyboard shortcut (Ctrl + Shift + B) to launch your game instead of the debug launcher.

**Comment by Tajfun86** [comment]
Roger that. I appreciate your help!

**Comment by HYBRID-BEING** [comment]
> The Playdate SDK version 1.12.3 and earlier only supports debugging on macOS. Unfortunately debugging is not yet available on Windows in the public SDK version. It will be available in Playdate SDK version 1.13+.

SDK 1.13.0 with debugging support for Windows/Linux is out for two years now, any chance you could make F5 work?
~~Granted, I'm currently developing in C (on Windows), so it might not be that relevant to me, but it would've been nice to be able to rebuild and launch simulator via F5.~~

**Comment by HYBRID-BEING** [comment]
@midouest 
Just to be clear, does [Playdate Debug 1.14.6+](https://marketplace.visualstudio.com/items/midouest.playdate-debug/changelog) support debugging on Windows/Linux now?
I am getting same error on Playdate Debug 1.18.0 (Windows 11) when trying to run build task via F5.
I'm currently developing in C though, so it might be the reason i'm getting the error...

**Comment by midouest** [comment]
@HYBRID-BEING Yes, the extension supports debugging on Windows/Linux.

**Comment by HYBRID-BEING** [comment]
@midouest, so, is it the language then? I actually solved the problem, but in a roundabout way...
<details>
 <summary>My `tasks.json`</summary>

```json
{
	"version": "2.0.0",
	"tasks": [
        {
            "label": "Playdate: Generate build files",
            "type": "shell",
            "command": [
                "&{",
                "Import-Module \"\"\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\"\"\";",
                "Enter-VsDevShell 79ccd2c4 -StartInPath .\\build -Arch amd64;",
                "cmake .. -G \"\"\"NMake Makefiles\"\"\";",
                "}"
            ],
            "group": {
                "kind": "build"
            },
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            }
        },
        {
            "label": "Playdate: Build",
            "type": "shell",
            "command": [
                "&{",
                "Import-Module \"\"\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\"\"\";",
                "Enter-VsDevShell 79ccd2c4 -StartInPath .\\build -Arch amd64;",
                "nmake;",
                "}"
            ],
            "problemMatcher": [
                "$msvc",
                "$pdc-external"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            }
        },
        {
            "label": "Playdate: Run",
            "type": "playdate-simulator",
            "problemMatcher": [
                "$pdc-external"
            ],
            "presentation": {
                "reveal": "always"
            }
        },
        {
            "label": "Playdate: Build and Run",
            "dependsOn": [
                "Playdate: Build",
                "Playdate: Run"
            ],
            "dependsOrder": "sequence",
            "problemMatcher": [],
            "group": {
                "kind": "build"
            }
        }
    ]
}
```
</details>

With default task set to "Playdate: Build", the [example `launch.json`](https://github.com/midouest/vscode-playdate-debug?tab=readme-ov-file#quick-setup) gives me the "could not connect to Playdate Simulator" error. If i make "Playdate: Build and Run" my default build task, error does not appear, and game starts in Simulator, but in just a second Simulator freezes and crashes without error.

Putting this in my `launch.json`, however, makes debugging work without a hitch:
```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Playdate: Debug",
        "type": "cppvsdbg",
        "program": "${env:PLAYDATE_SDK_PATH}/bin/PlaydateSimulator.exe",
        "request": "launch",
        "preLaunchTask": "${defaultBuildTask}"
      }
    ]
  }
```

**Comment by midouest** [comment]
If your game is only in C, then the simulator does not start the Lua runtime and there is nothing for this debugger extension to connect to. Using a C debugger is the correct choice.

**Comment by HYBRID-BEING** [comment]
Thanks.
Wonder why Simulator crashes on me, though. But, I guess there's not much point in using the extension for me, then?
~~Well, at least maybe someone will stumble upon my post here and find my configs useful.~~
