### ISSUE TITLE
subsequent run command does not upload new code to simulator

### ISSUE THREAD

**Issue by jkozniewski** [midouest/vscode-playdate-debug#15]
It seems that subsequent run commands do not upload new pdx
onto the console, the simulator seems to get restarted / refreshed but
it's running old version of the code. Right now I need to manually click the 
"stop debug session" icon before running it again, which I guess is not really
the intended workflow ? 
(Using Mac OS)

**Comment by midouest** [comment]
Are you referring to the "Run/Debug file in Playdate Simulator" button in the editor window?

<img width="203" alt="Screenshot 2023-01-06 at 7 42 47 PM" src="https://user-images.githubusercontent.com/67558040/211125640-43796e68-afd3-46b2-89c2-79f954e74ebe.png">

**Comment by jkozniewski** [comment]
yes, exactly 
<img width="511" alt="Screenshot 2023-01-07 at 16 20 13" src="https://user-images.githubusercontent.com/6979983/211157967-b58b232c-db30-4cd6-ac41-018b3e1603d6.png">

**Comment by jkozniewski** [comment]
as you have closed the issue - is it fixed now ?
just relaunched vs code and it still behaves as previously, or it just won't work for the button as you suggest here - https://github.com/midouest/vscode-playdate-debug/issues/14#issuecomment-1374344854 
sorry quite confused with the proper workflow here ;)

**Comment by midouest** [comment]
The issue is fixed, but the fix is not yet released.

The original workflow for the extension was to use the tasks + launcher to build/debug on the simulator. I added the Run/Debug file in Simulator button recently as a way to get started with zero additional configuration. I'm still trying to figure out the best way to communicate all that in the README 😄

**Comment by midouest** [comment]
Fix released in v1.10.0
