### ISSUE TITLE
SDK versioning or other solutions?

### ISSUE THREAD

**Issue by Kidlike** [midouest/vscode-playdate-debug#17]
Hi,

Is it possible to change the version of the PlaydateSDK?

Or could I point to an external folder that contains a newer copy of the PlaydateSDK? (that I manage myself).

Or any other ideas? I'm very new to programming for the Playdate.

Thanks!

**Comment by midouest** [comment]
Yes, you can do this with the `playdate-debug.sdkPath` configuration setting. See the [override-configuration](https://github.com/midouest/vscode-playdate-debug/tree/main/fixtures/workspace/override-configuration) fixture for an example.
