### ISSUE TITLE
gnome-terminal only

### ISSUE THREAD

**Issue by Kidlike** [midouest/vscode-playdate-debug#18]
https://github.com/midouest/vscode-playdate-debug/blob/01c8e8b5b2133b7a020149c75835f7dc2af9d4f1/src/simulator/createSimulatorExecutionLinux.ts#L39

could this become configurable?

**Comment by midouest** [comment]
Good idea!

**Comment by Kidlike** [comment]
fyi, I had to slightly change syntax for `konsole`. it has to be like `konsole -e /bin/bash -c <...>` instead of `gnome-terminal -- <...>`. Not sure how to handle this properly with config... maybe something like command prefix :man_shrugging:

**Comment by midouest** [comment]
Good to know. Something simple like a prefix is probably the way to go. 

I’m hoping to rework the whole Linux code path once debugging is supported. Launching the Simulator from a gnome-terminal is a workaround for an issue I encountered when I attempted to launch it as a detached child process.

**Comment by midouest** [comment]
I've just published version 1.13 of the extension as a pre-release. It should be available on the marketplace any minute! 🤞 Let me know if the new changes work for you!

The simulator will now launch in VSCode's integrated terminal instead of a Gnome terminal.
