### ISSUE TITLE
Building with make

### ISSUE THREAD

**Issue by jonagill** [midouest/vscode-playdate-debug#27]
Is it possible to configure this extension to build with `make` rather than `pdc` to allow the development of games using custom C functions?  The Nova Playdate plugin has a `playdate.build-type` argument that allows you to compile via `make`, but I can't see anything similar in your VS Code plugin.

I understand this is probably a huge feature ask, but VS Code is a lot nicer for Lua development than Nova in my opinion, so it would be fantastic if there was a way to still build and launch my game directly from Code now I've had to start adding some custom C functions for performance reasons.

**Comment by midouest** [comment]
I’ve been thinking about adding support for make, but I am definitely concerned that it will be a huge feature as you say.

Have you tried using the [Makefile extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools) to build your game? You may be able to replace the PDC task from this extension with a build task from the Makefile extension. Then you would launch the PDX bundle from the make task with the simulator task in this extension.

**Comment by midouest** [comment]
Here is a guide on how to setup VSCode to build and debug mixed C/Lua projects: [Guide: Debugging mixed Lua/C projects with VSCode](https://devforum.play.date/t/guide-debugging-mixed-lua-c-projects-with-vscode/15473)
