### ISSUE TITLE
Version 1.14.8 is very large

### ISSUE THREAD

**Issue by Riari** [midouest/vscode-playdate-debug#31]
Hi,

I'm not sure how new releases are done, but the latest release (1.14.8) seems to be way bigger than it should be. The [VSIX on the marketplace](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/midouest/vsextensions/playdate-debug/1.14.8/vspackage) is 175MB, whereas 1.14.6 is just 3.4MB.

**Comment by midouest** [comment]
Thank you for catching this! I had noticed that the releases were taking way longer to publish/verify but I couldn't figure out what happened. Fixed in 1.14.10, available shortly. Sorry about that!
