### ISSUE TITLE
relative path in settings

### ISSUE THREAD

**Issue by loudoweb** [midouest/vscode-playdate-debug#5]
Looks like the path in settings must be absolute as it tries to open from the installation folder of vscode if you set a relative path.

Is it possible to use a relative path from the project folder and not from vscode folder?

I'm on Windows if that helps.

**Comment by midouest** [comment]
Thanks for reporting this! It is fixed in c9f1a839efafc16fcf7ed2b8372e6e724f3f47ec and published to the VSCode marketplace.
