### ISSUE TITLE
Breakpoints no longer work in VSCode 1.73.x

### ISSUE THREAD

**Issue by Minalien** [midouest/vscode-playdate-debug#7]
Breakpoints (both regular breakpoints and break-on-exceptions) fail to work in Visual Studio Code 1.73.0 and 1.73.1

Not sure if this is the cause of the break, but there do appear to be changes to the debug adapter protocol in 1.73? Not sure if this is something that needs adjustment in this extension, or something needing updating in the simulator itself.
https://code.visualstudio.com/updates/v1_73#_debug-adapter-protocol

For now, workaround is to roll back VSCode to 1.72 (September 2022) or earlier.

**Comment by midouest** [comment]
Thanks for reporting this! I am looking into it.

FWIW It looks like breakpoints do still work in 1.73.x, but only if you set them after the debug adapter session has been launched. It looks like VSCode is not sending the initial breakpoints to the Playdate Simulator for some reason.

**Comment by midouest** [comment]
Fixed by a6e1eaebc3bcd8906ef4c7268950d8b92b1b5abf

**Comment by Minalien** [comment]
Confirmed working for me in 1.73.1, thanks so much! 💜
